//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToshibaPosSinkronizimi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSSinkronizimi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if not exists(
        ///select 1 from sys.schemas where name =&apos;POS&apos;
        ///)
        ///Begin 
        /// exec (&apos;CREATE SCHEMA [POS] AUTHORIZATION [dbo]&apos;)
        ///End
        ///Go --
        ///
        ///IF EXISTS (SELECT * FROM sys.objects 
        ///			  WHERE object_id = OBJECT_ID(N&apos;POS.POS_GjejeZbritjenNeArtikull&apos;) ) 
        ///			  begin
        ///			  Drop  Function  POS.POS_GjejeZbritjenNeArtikull
        ///			  End 
        ///			  Go -- 
        ///CREATE FUNCTION POS.[POS_GjejeZbritjenNeArtikull]
        ///(@ArtikulliId int,@Sasia Decimal(18,3))
        ///RETURNS Decimal(18,2)
        ///AS
        ///BEGIN
        ///
        ///	DECLARE @ResultVar Decimal(18,3)
        ///
        ///Select t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Funksionet {
            get {
                return ResourceManager.GetString("Funksionet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  if not exists(
        ///select 1 from sys.schemas where name =&apos;POS&apos;
        ///)
        ///Begin 
        /// exec (&apos;CREATE SCHEMA [POS] AUTHORIZATION [dbo]&apos;)
        ///End
        ///Go --
        ///
        ///IF EXISTS (SELECT * FROM sys.objects 
        ///			  WHERE object_id = OBJECT_ID(N&apos;POS.POS_GjenerimiKomandaveFiskale_Sp&apos;) ) 
        ///			  begin
        ///			  Drop  Procedure  POS.POS_GjenerimiKomandaveFiskale_Sp
        ///			  End
        ///Go --
        ///			  CREATE PROCEDURE [POS].[POS_GjenerimiKomandaveFiskale_Sp] --&apos;Operatori&apos;,10038
        ///@Kerkesa VARCHAR(100),
        ///@OperatoriId int = null
        ///AS
        ///DECLARE @Komanda AS VARCHAR(MAX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KomandatFiskale {
            get {
                return ResourceManager.GetString("KomandatFiskale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///IF not EXISTS (SELECT 1 FROM SYS.key_constraints	WHERE name = &apos;UQ_PMPKartelat_KodiKarteles&apos;)
        ///begin
        ///		  ALTER TABLE [dbo].[PMPKartelat] ADD CONSTRAINT [UQ_PMPKartelat_KodiKarteles] UNIQUE (KodiKarteles)
        ///End
        ///Go --
        ///IF NOT EXISTS (SELECT 1 FROM sys.indexes	WHERE name = &apos;IX_PMPTransaksionet_DerguarNeServer&apos;)
        ///begin
        ///		   create nonclustered INDEX [IX_PMPTransaksionet_DerguarNeServer] ON [dbo].[PMPTransaksionet] (DerguarNeServer) 
        ///End
        ///else
        ///Begin 
        ///ALTER INDEX [IX_PMPTransaksionet_DerguarNeServer] ON dbo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ndryshimet {
            get {
                return ResourceManager.GetString("Ndryshimet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if not exists(
        ///select 1 from sys.schemas where name =&apos;POS&apos;
        ///)
        ///Begin 
        /// exec (&apos;CREATE SCHEMA POS AUTHORIZATION dbo&apos;)
        ///End
        ///Go --
        ///IF EXISTS (SELECT * FROM sys.objects 
        ///			  WHERE object_id = OBJECT_ID(N&apos;POS.Mxh_OperatoretQasjaSelect_sp&apos;) ) 
        ///			  begin
        ///			  Drop  Procedure  POS.Mxh_OperatoretQasjaSelect_sp
        ///			  End
        ///Go --
        ///
        ///CREATE PROCEDURE POS.Mxh_OperatoretQasjaSelect_sp
        ///(@Operatori varchar (100) =null,
        ///@Pass varchar (100)=null
        ///) 
        ///as begin 
        /// 
        ///Select O.Id,Emri,Mbiemri,GrupiId,Operatori,Statusi
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProceduratLokal {
            get {
                return ResourceManager.GetString("ProceduratLokal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RikrijoDB {
            get {
                return ResourceManager.GetString("RikrijoDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///IF NOT EXISTS (SELECT * FROM sys.objects 
        ///			  WHERE object_id = OBJECT_ID(N&apos;PMPLlog&apos;) AND type in (N&apos;U&apos;)) 
        ///			  begin
        ///			  CREATE TABLE [dbo].[PMPLlog]
        ///(
        ///      [Id] [int] IDENTITY(1,1) PRIMARY KEY 
        ///    , [ORganizataId] INT NOT NULL 
        ///	, [DispenzeriId] INT NOT NULL 
        ///	, [RFID] VARCHAR(50)  NULL 
        ///	, [DataRegjistrimit] DATETIME NOT NULL DEFAULT (GETDATE())
        ///	, [QM1] VARCHAR(50) NULL  
        ///	, [QM2] VARCHAR(50) NULL 
        ///	, [QM3] VARCHAR(50) NULL 
        ///	, [QM4] VARCHAR(50) NULL 
        ///	, [QM5] VARCHAR(50) NULL 
        ///	,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tabelat {
            get {
                return ResourceManager.GetString("Tabelat", resourceCulture);
            }
        }
    }
}
